import type { HeartPart, CirculationPath, ModelMeta } from './contracts'

export const LOCAL_PARTS: HeartPart[] = [
  {
    id: 'left-atrium',
    nameZh: '左心房',
    nameEn: 'Left Atrium',
    type: 'chamber',
    layers: {
      anatomy: '左心房位于心脏左上方，壁厚约2-3mm，是四个心腔中壁最薄的。它通过肺静脉接收来自肺部的含氧血，经二尖瓣将血液送入左心室。',
      physiology: '左心房的主要功能是收集和储存肺静脉回流的含氧血，在心室舒张期通过二尖瓣将血液被动和主动地充盈到左心室。',
    },
    relations: {
      connectsTo: ['mitral-valve', 'pulmonary-vein'],
      supplies: ['left-ventricle'],
      receivesFrom: ['pulmonary-vein'],
      affectedBy: [],
    },
    circulationPaths: ['pulmonary-loop', 'systemic-loop'],
    funFact: '左心房的心耳是血栓形成的好发部位，房颤患者尤其需要注意。',
  },
  {
    id: 'left-ventricle',
    nameZh: '左心室',
    nameEn: 'Left Ventricle',
    type: 'chamber',
    layers: {
      anatomy: '左心室位于心脏左下方，壁厚约13-15mm，是四个心腔中壁最厚的。其厚实的肌壁为体循环提供强大的泵血动力，经主动脉瓣将含氧血射入主动脉。',
      physiology: '左心室是体循环的起始泵，收缩时产生约120mmHg的压力，将含氧血通过主动脉输送到全身各器官和组织，是心脏最重要的功能单元。',
    },
    relations: {
      connectsTo: ['aortic-valve', 'mitral-valve'],
      supplies: ['aorta'],
      receivesFrom: ['left-atrium'],
      affectedBy: [],
    },
    circulationPaths: ['systemic-loop'],
    funFact: '左心室壁的厚度是右心室的3倍，因为它需要将血液泵到全身而不是仅到肺部。',
  },
  {
    id: 'right-atrium',
    nameZh: '右心房',
    nameEn: 'Right Atrium',
    type: 'chamber',
    layers: {
      anatomy: '右心房位于心脏右上方，接收上腔静脉和下腔静脉回流的脱氧血。窦房结位于右心房上壁，是心脏的天然起搏器。',
      physiology: '右心房收集全身回流的脱氧血，通过三尖瓣将血液送入右心室。窦房结产生电信号控制心跳节律，是心脏传导系统的起点。',
    },
    relations: {
      connectsTo: ['tricuspid-valve', 'superior-vena-cava', 'inferior-vena-cava'],
      supplies: ['right-ventricle'],
      receivesFrom: ['superior-vena-cava', 'inferior-vena-cava'],
      affectedBy: [],
    },
    circulationPaths: ['systemic-loop', 'pulmonary-loop'],
    funFact: "右心房中的窦房结每分钟产生60-100次电脉冲，是心脏的'司令部'。",
  },
  {
    id: 'right-ventricle',
    nameZh: '右心室',
    nameEn: 'Right Ventricle',
    type: 'chamber',
    layers: {
      anatomy: '右心室位于心脏右前方，壁厚约3-5mm，明显薄于左心室。它通过肺动脉瓣将脱氧血泵入肺动脉，进入肺循环进行气体交换。',
      physiology: '右心室是肺循环的动力源，收缩时产生约25mmHg的压力（远低于左心室），将脱氧血送入肺部进行氧合，压力较低是因为肺循环阻力远小于体循环。',
    },
    relations: {
      connectsTo: ['pulmonary-valve', 'tricuspid-valve'],
      supplies: ['pulmonary-artery'],
      receivesFrom: ['right-atrium'],
      affectedBy: [],
    },
    circulationPaths: ['pulmonary-loop'],
    funFact: '右心室虽然壁薄，但在肺循环中不可或缺，肺栓塞时会面临巨大压力负荷。',
  },
  {
    id: 'aorta',
    nameZh: '主动脉',
    nameEn: 'Aorta',
    type: 'vessel',
    layers: {
      anatomy: '主动脉是人体最大的动脉，直径约2.5-3cm，起始于左心室的主动脉瓣。它先上行形成升主动脉，弯曲形成主动脉弓，再下行形成降主动脉，分支供应全身。',
      physiology: '主动脉接受左心室泵出的含氧血，通过其各级分支将血液输送至全身器官。主动脉壁富有弹性，在心室舒张期通过弹性回缩维持持续的血流。',
    },
    relations: {
      connectsTo: ['aortic-valve'],
      supplies: [],
      receivesFrom: ['left-ventricle'],
      affectedBy: [],
    },
    circulationPaths: ['systemic-loop'],
    funFact: '主动脉每分钟输送约5升血液，一天泵送的血液量足以填满一个小型游泳池。',
  },
  {
    id: 'pulmonary-artery',
    nameZh: '肺动脉',
    nameEn: 'Pulmonary Artery',
    type: 'vessel',
    layers: {
      anatomy: '肺动脉起始于右心室的肺动脉瓣，是唯一运送脱氧血的动脉。它在主动脉弓下方分为左右两支，分别进入左右肺，在肺泡毛细血管处进行气体交换。',
      physiology: '肺动脉将脱氧血从右心室输送到肺部，在肺泡毛细血管中释放二氧化碳并摄取氧气，完成气体交换后变为含氧血经肺静脉回流。',
    },
    relations: {
      connectsTo: ['pulmonary-valve'],
      supplies: [],
      receivesFrom: ['right-ventricle'],
      affectedBy: [],
    },
    circulationPaths: ['pulmonary-loop'],
    funFact: '肺动脉是唯一携带脱氧血的动脉，而肺静脉是唯一携带含氧血的静脉——这是解剖学的有趣反例。',
  },
  {
    id: 'superior-vena-cava',
    nameZh: '上腔静脉',
    nameEn: 'Superior Vena Cava',
    type: 'vessel',
    layers: {
      anatomy: '上腔静脉是收集头部、上肢和胸部的脱氧血回流至右心房的大静脉，长约7cm，由左右头臂静脉汇合而成，开口于右心房上方。',
      physiology: '上腔静脉收集人体上半身的静脉回流，依靠重力辅助和胸腔负压将脱氧血送回右心房，参与完成体循环的回流阶段。',
    },
    relations: {
      connectsTo: [],
      supplies: [],
      receivesFrom: ['right-atrium'],
      affectedBy: [],
    },
    circulationPaths: ['systemic-loop'],
    funFact: '上腔静脉综合征（SVC综合征）常由肿瘤压迫引起，可导致面部和上肢严重水肿。',
  },
  {
    id: 'inferior-vena-cava',
    nameZh: '下腔静脉',
    nameEn: 'Inferior Vena Cava',
    type: 'vessel',
    layers: {
      anatomy: '下腔静脉是人体最大的静脉，收集腹部、骨盆和下肢的脱氧血回流至右心房。它沿脊柱右前方上行，穿过膈肌后开口于右心房下方。',
      physiology: '下腔静脉收集人体下半身的静脉回流，携带大量脱氧血返回右心房，其血流量约占全身静脉回流的三分之二。',
    },
    relations: {
      connectsTo: [],
      supplies: [],
      receivesFrom: ['right-atrium'],
      affectedBy: [],
    },
    circulationPaths: ['systemic-loop'],
    funFact: '下腔静脉的直径可达3cm，是人体管腔最大的静脉，妊娠晚期增大的子宫可压迫它导致仰卧位低血压。',
  },
  {
    id: 'pulmonary-vein',
    nameZh: '肺静脉',
    nameEn: 'Pulmonary Vein',
    type: 'vessel',
    layers: {
      anatomy: '肺静脉共四条（左右各两条），是唯一运送含氧血的静脉。它们从肺部出发，将经过气体交换的含氧血输送至左心房，完成肺循环。',
      physiology: '肺静脉将肺部氧合后的含氧血输送至左心房，是肺循环的最终回流通道，确保含氧血进入体循环供给全身。',
    },
    relations: {
      connectsTo: [],
      supplies: [],
      receivesFrom: ['left-atrium'],
      affectedBy: [],
    },
    circulationPaths: ['pulmonary-loop'],
    funFact: '肺静脉是房颤射频消融术的重要靶点，因为触发房颤的异常电信号常起源于肺静脉开口处。',
  },
  {
    id: 'tricuspid-valve',
    nameZh: '三尖瓣',
    nameEn: 'Tricuspid Valve',
    type: 'valve',
    layers: {
      anatomy: '三尖瓣位于右心房与右心室之间，由三个瓣叶（前叶、后叶、隔叶）组成，通过腱索与乳头肌相连，防止血液在心室收缩时反流回右心房。',
      physiology: '三尖瓣在心室舒张期开放，允许脱氧血从右心房流入右心室；在心室收缩期关闭，防止血液逆流回右心房，确保血液单向流入肺动脉。',
    },
    relations: {
      connectsTo: [],
      supplies: ['right-ventricle'],
      receivesFrom: ['right-atrium'],
      affectedBy: [],
    },
    circulationPaths: ['pulmonary-loop'],
    funFact: '三尖瓣是心脏中最大的瓣膜，其瓣叶面积约为二尖瓣的两倍。',
  },
  {
    id: 'mitral-valve',
    nameZh: '二尖瓣',
    nameEn: 'Mitral Valve',
    type: 'valve',
    layers: {
      anatomy: '二尖瓣又称僧帽瓣，位于左心房与左心室之间，由两个瓣叶（前叶和后叶）组成。前叶较大，后叶较小，通过腱索与左心室的乳头肌相连。',
      physiology: '二尖瓣在心室舒张期开放，允许含氧血从左心房流入左心室；在心室收缩期关闭，承受左心室高压，防止血液逆流回左心房，确保血液全部射入主动脉。',
    },
    relations: {
      connectsTo: [],
      supplies: ['left-ventricle'],
      receivesFrom: ['left-atrium'],
      affectedBy: [],
    },
    circulationPaths: ['systemic-loop'],
    funFact: '二尖瓣脱垂是最常见的心脏瓣膜疾病，影响约2%的人群，多数无需治疗。',
  },
  {
    id: 'pulmonary-valve',
    nameZh: '肺动脉瓣',
    nameEn: 'Pulmonary Valve',
    type: 'valve',
    layers: {
      anatomy: '肺动脉瓣位于右心室出口与肺动脉之间，由三个半月形瓣叶组成，是右心室流出道的最后一道关卡。',
      physiology: '肺动脉瓣在心室收缩期开放，允许脱氧血从右心室射入肺动脉进入肺循环；在心室舒张期关闭，防止肺动脉中的血液反流回右心室。',
    },
    relations: {
      connectsTo: [],
      supplies: ['pulmonary-artery'],
      receivesFrom: ['right-ventricle'],
      affectedBy: [],
    },
    circulationPaths: ['pulmonary-loop'],
    funFact: '肺动脉瓣是最少发生病变的心脏瓣膜，但先天性肺动脉瓣狭窄是最常见的先天性心脏病之一。',
  },
  {
    id: 'aortic-valve',
    nameZh: '主动脉瓣',
    nameEn: 'Aortic Valve',
    type: 'valve',
    layers: {
      anatomy: '主动脉瓣位于左心室出口与主动脉之间，由三个半月形瓣叶组成（左冠瓣、右冠瓣、无冠瓣），其中左右冠瓣的开口分别是左右冠状动脉的入口。',
      physiology: '主动脉瓣在心室收缩期开放，允许含氧血从左心室射入主动脉进入体循环；在心室舒张期关闭，承受主动脉高压，防止血液反流回左心室，同时保证冠状动脉灌注。',
    },
    relations: {
      connectsTo: [],
      supplies: ['aorta'],
      receivesFrom: ['left-ventricle'],
      affectedBy: [],
    },
    circulationPaths: ['systemic-loop'],
    funFact: '主动脉瓣承受的压力是所有心脏瓣膜中最大的，这也是它最容易发生退行性病变的原因之一。',
  },
  {
    id: 'septum',
    nameZh: '室间隔',
    nameEn: 'Septum',
    type: 'structure',
    layers: {
      anatomy: '室间隔是分隔左右心室的厚实肌壁，上部较薄为膜部，下部厚实为肌部。室间隔的存在确保含氧血和脱氧血互不混合，是体循环和肺循环独立运行的关键结构。',
      physiology: '室间隔在心室收缩期与左右心室壁协同收缩，为两侧心室提供结构支撑。室间隔膜部是室间隔缺损的好发部位，缺损会导致左右心血液异常分流。',
    },
    relations: {
      connectsTo: ['left-ventricle', 'right-ventricle'],
      supplies: [],
      receivesFrom: [],
      affectedBy: [],
    },
    circulationPaths: ['systemic-loop', 'pulmonary-loop'],
    funFact: '先天性室间隔缺损是最常见的先天性心脏病，约占所有先心病的25-30%。',
  },
]

export const LOCAL_PATHS: CirculationPath[] = [
  {
    id: 'systemic-loop',
    nameZh: '体循环',
    nameEn: 'Systemic Circulation',
    nodes: [
      { partId: 'left-ventricle', position: [0, 0.5, 0.3] },
      { partId: 'aorta', position: [0.3, 1.2, 0.2] },
      { partId: 'superior-vena-cava', position: [-0.4, 1.3, -0.1] },
      { partId: 'inferior-vena-cava', position: [-0.3, -0.8, -0.1] },
      { partId: 'right-atrium', position: [-0.3, 0.6, 0.2] },
    ],
    edges: [
      { from: 'left-ventricle', to: 'aorta', direction: 'oxy', duration: 2.0, delay: 0, oxygenLevel: 1.0 },
      { from: 'aorta', to: 'superior-vena-cava', direction: 'deoxy', duration: 4.0, delay: 2.0, oxygenLevel: 0.6 },
      { from: 'aorta', to: 'inferior-vena-cava', direction: 'deoxy', duration: 4.0, delay: 2.0, oxygenLevel: 0.4 },
      { from: 'superior-vena-cava', to: 'right-atrium', direction: 'deoxy', duration: 1.5, delay: 6.0, oxygenLevel: 0.2 },
      { from: 'inferior-vena-cava', to: 'right-atrium', direction: 'deoxy', duration: 1.5, delay: 6.0, oxygenLevel: 0.2 },
    ],
    animationSpeed: 1.0,
  },
  {
    id: 'pulmonary-loop',
    nameZh: '肺循环',
    nameEn: 'Pulmonary Circulation',
    nodes: [
      { partId: 'right-ventricle', position: [0, -0.2, 0.3] },
      { partId: 'pulmonary-artery', position: [0.2, 1.0, -0.2] },
      { partId: 'pulmonary-vein', position: [-0.2, 1.0, 0.3] },
      { partId: 'left-atrium', position: [0.2, 0.7, 0.3] },
    ],
    edges: [
      { from: 'right-ventricle', to: 'pulmonary-artery', direction: 'deoxy', duration: 2.0, delay: 0, oxygenLevel: 0.2 },
      { from: 'pulmonary-artery', to: 'pulmonary-vein', direction: 'oxy', duration: 4.0, delay: 2.0, oxygenLevel: 0.6 },
      { from: 'pulmonary-vein', to: 'left-atrium', direction: 'oxy', duration: 1.5, delay: 6.0, oxygenLevel: 1.0 },
    ],
    animationSpeed: 1.0,
  },
]

export const LOCAL_MODEL_META: ModelMeta = {
  partIds: [
    'left-atrium', 'left-ventricle', 'right-atrium', 'right-ventricle',
    'aorta', 'pulmonary-artery', 'superior-vena-cava', 'inferior-vena-cava', 'pulmonary-vein',
    'tricuspid-valve', 'mitral-valve', 'pulmonary-valve', 'aortic-valve',
    'septum',
  ],
  colorMapping: {
    'left-atrium': { base: '#e74c3c', oxy: '#ff4444', deoxy: '#6622aa' },
    'left-ventricle': { base: '#c0392b', oxy: '#ff3333', deoxy: '#5522aa' },
    'right-atrium': { base: '#8e44ad', oxy: '#cc44aa', deoxy: '#4422cc' },
    'right-ventricle': { base: '#7d3c98', oxy: '#bb44aa', deoxy: '#3311aa' },
    'aorta': { base: '#e74c3c', oxy: '#ff4444', deoxy: '#6622aa' },
    'pulmonary-artery': { base: '#8e44ad', oxy: '#cc44aa', deoxy: '#4422cc' },
    'superior-vena-cava': { base: '#8e44ad', oxy: '#cc44aa', deoxy: '#4422cc' },
    'inferior-vena-cava': { base: '#8e44ad', oxy: '#cc44aa', deoxy: '#4422cc' },
    'pulmonary-vein': { base: '#e74c3c', oxy: '#ff4444', deoxy: '#6622aa' },
    'tricuspid-valve': { base: '#f39c12', oxy: '#f39c12', deoxy: '#f39c12' },
    'mitral-valve': { base: '#f39c12', oxy: '#f39c12', deoxy: '#f39c12' },
    'pulmonary-valve': { base: '#f39c12', oxy: '#f39c12', deoxy: '#f39c12' },
    'aortic-valve': { base: '#f39c12', oxy: '#f39c12', deoxy: '#f39c12' },
    'septum': { base: '#bdc3c7', oxy: '#bdc3c7', deoxy: '#bdc3c7' },
  },
  occlusionMap: {
    'left-ventricle': ['septum', 'left-atrium'],
    'right-ventricle': ['septum', 'right-atrium'],
    'left-atrium': ['aorta', 'pulmonary-vein'],
    'right-atrium': ['superior-vena-cava', 'inferior-vena-cava'],
    'tricuspid-valve': ['right-atrium', 'right-ventricle'],
    'mitral-valve': ['left-atrium', 'left-ventricle'],
    'pulmonary-valve': ['pulmonary-artery', 'right-ventricle'],
    'aortic-valve': ['aorta', 'left-ventricle'],
  },
}
